# Generated by Django 3.2.10 on 2022-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20221004_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.CharField(blank=True, default='0', max_length=256),
        ),
    ]
