# Generated by Django 3.2.10 on 2022-10-06 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_alter_userrole_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectedpermission',
            options={'ordering': ['id'], 'verbose_name_plural': 'SelectedPermission'},
        ),
        migrations.AddField(
            model_name='userrole',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_owner', to='accounts.user'),
            preserve_default=False,
        ),
    ]
