"""
Django settings for posox project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from django.utils import timezone
from .jazzmin_settings import JAZZMIN_SETTINGS
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
JAZZMIN_SETTINGS = JAZZMIN_SETTINGS
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PROJECT_ROOT = os.path.dirname(__file__)

AUTH_USER_MODEL = 'accounts.User'  # use our custom User model (not Django's)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-nb@)%wg)^%1i%+m9s_q*an4=anyxg0)^4suzs(7*96n@zl!fbm")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    BASE_URL = "http://127.0.0.1:8585"
else:
    BASE_URL = "https://posox.site.uz"

SMS_TIMEOUT_MIN = 2

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third-party apps
    'corsheaders',
    # 'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'import_export',

    'apps.accounts.apps.AccountsConfig',
    'apps.outlets.apps.OutletsConfig',
    'apps.address.apps.AddressConfig',
    'apps.billings.apps.BillingsConfig',
    'apps.products.apps.ProductsConfig',
    'apps.reports.apps.ReportsConfig',
    'apps.upload.apps.UploadConfig',
    'apps.dashboard.apps.DashboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'posox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'posox.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
    # 'DEFAULT_PERMISSION_CLASSES':
    #     ('rest_framework.permissions.AllowAny',),
    # "EXCEPTION_HANDLER": "apps.core.exception.exception_handler.status_code_handler"
}

LANGUAGE_CODE = 'uz'

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Translations

gettext = lambda s: s

LANGUAGES = (
    ('uz', gettext('Uzbek')),
    ('ru', gettext('Russian'))
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "handlers": {
#         "console": {
#             "level": "DEBUG",
#             "class": "logging.StreamHandler",
#         },
#         "logfile": {
#             "level": "DEBUG",
#             "class": "logging.FileHandler",
#             "filename": os.path.join(BASE_DIR, "log", "logfile"),
#         },
#     },
#     "root": {
#         "level": "DEBUG",
#         "handlers": ["console", "logfile"]
#     },
# }

SWAGGER_SETTINGS = {
    "DEFAULT_AUTO_SCHEMA_CLASS": "apps.core.swagger_schemas.GlobalAutoSchema"
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timezone.timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timezone.timedelta(days=35),
}

CORS_ORIGIN_ALLOW_ALL = True  # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:3000",
    "http://api.posox.site.uz",
    "https://api.posox.site.uz",
    "https://posox.site.uz",
    "http://posox.site.uz",
    "https://api.posox.uz",
    "https://posox.netlify.app",
    "http://posox.netlify.app",
]

INVOICE_EXPIRE_DAY = 10
PX_ROBOT_PHONE = "+000000000000"
