# Generated by Django 3.2.10 on 2022-09-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_id', models.CharField(max_length=120, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('comment', models.TextField(blank=True)),
                ('expire_in', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (4, 'Returned')], default=1)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_user', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutletExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.IntegerField(choices=[(1, 'Uzs'), (2, 'Usd')], default=1)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_expense', to='outlets.outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pay_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (4, 'Cash Card'), (8, 'Credit')], default=1)),
                ('amount_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amount_card', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Unpaid'), (4, 'Progress'), (8, 'Completed')], default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receipt', to='reports.invoice')),
            ],
            options={
                'verbose_name_plural': 'InvoiceReceipts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through_invoice_product', to='products.outletproduct')),
            ],
            options={
                'verbose_name_plural': 'InvoiceProducts',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='invoice_products', through='reports.InvoiceProduct', to='products.OutletProduct'),
        ),
    ]
