# Generated by Django 3.2.10 on 2022-09-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['id'], 'verbose_name_plural': '    Invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoiceproduct',
            options={'ordering': ['id'], 'verbose_name_plural': '   InvoiceProducts'},
        ),
        migrations.AlterModelOptions(
            name='invoicereceipt',
            options={'ordering': ['id'], 'verbose_name_plural': '  InvoiceReceipts'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Unpaid'), (4, 'Paid'), (8, 'Refund')], default=1),
        ),
        migrations.AlterField(
            model_name='invoicereceipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_receipt', to='reports.invoice'),
        ),
    ]
