# Generated by Django 3.2.10 on 2022-09-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_auto_20220909_0125'),
        ('reports', '0002_auto_20220909_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cashier',
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_bln', to='billings.billingaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_bln', to='billings.billingaccount'),
        ),
    ]
