# Generated by Django 3.2.10 on 2022-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_invoice_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicereceipt',
            name='receipt_no',
            field=models.CharField(default=0, max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
