# Generated by Django 3.2.10 on 2022-09-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['-id'], 'verbose_name_plural': '  Outlets'},
        ),
        migrations.AlterModelOptions(
            name='outletmember',
            options={'ordering': ['-id'], 'verbose_name_plural': ' OutletMembers'},
        ),
        migrations.AlterField(
            model_name='outletcashbox',
            name='outlet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop_cash_box', to='outlets.outlet'),
        ),
    ]
