# Generated by Django 3.2.10 on 2022-09-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0003_outletcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletmember',
            name='type',
        ),
    ]
