# Generated by Django 3.2.10 on 2022-09-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_auto_20220910_0729'),
        ('outlets', '0004_remove_outletmember_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletcustomer',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_balance', to='billings.userbalance'),
        ),
        migrations.AlterField(
            model_name='outletcustomer',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_user', to='outlets.outlet'),
        ),
        migrations.AlterField(
            model_name='outletcustomer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2),
        ),
    ]
