# Generated by Django 3.2.10 on 2022-09-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0005_auto_20220910_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='type',
            field=models.IntegerField(choices=[(1, 'Main'), (2, 'Branch')], default=2),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (4, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='outletmember',
            name='status',
            field=models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2),
        ),
    ]
