# Generated by Django 3.2.10 on 2022-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlets', '0006_auto_20220910_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmember',
            name='type',
            field=models.IntegerField(choices=[(1, 'Member'), (2, 'Owner')], default=1),
        ),
    ]
