# Generated by Django 3.2.10 on 2022-09-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('card_number', models.CharField(blank=True, max_length=50)),
                ('expire_date', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'Cashbox'), (2, 'Owner'), (4, 'Admin'), (8, 'Manager'), (16, 'Customer')], default=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BillingProfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('total', models.CharField(max_length=255)),
                ('currency', models.IntegerField(choices=[(1, 'Uzs'), (2, 'Usd')], default=1)),
                ('outlet', models.IntegerField(choices=[(1, 'Main'), (2, 'Branch'), (4, 'Inactive'), (8, 'Deleted')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Transfers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserBalances',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_method', models.IntegerField(choices=[(1, 'Terminal'), (2, 'Cash'), (4, 'Credit'), (8, 'Vip Payment')], default=2)),
                ('reason', models.IntegerField(blank=True, choices=[(1, 'Buying'), (2, 'Selling'), (4, 'Credit')], null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Progress'), (4, 'Failed'), (8, 'Completed')], default=1)),
                ('comment', models.TextField(blank=True)),
                ('currency', models.IntegerField(choices=[(1, 'Uzs'), (2, 'Usd')], default=1)),
                ('balance_updated', models.BooleanField(default=False)),
                ('created_time', models.CharField(blank=True, max_length=255)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='reports.invoice')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_user', to='billings.billingaccount')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_cash', to='outlets.outletcashbox')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['id'],
            },
        ),
    ]
