# Generated by Django 3.2.10 on 2022-09-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaccount',
            options={'ordering': ['-id'], 'verbose_name_plural': '   BillingProfiles'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id'], 'verbose_name_plural': ' Transactions'},
        ),
        migrations.AlterModelOptions(
            name='userbalance',
            options={'ordering': ['-id'], 'verbose_name_plural': '  UserBalances'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='destination_bln', to='billings.billingaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin_bln', to='billings.billingaccount'),
            preserve_default=False,
        ),
    ]
