# Generated by Django 3.2.10 on 2022-09-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_auto_20220910_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='pay_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (4, 'Cash Card'), (8, 'Credit'), (16, 'Terminal'), (32, 'Vip Payment')], default=1),
        ),
    ]
