# Generated by Django 3.2.10 on 2022-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_alter_transaction_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.IntegerField(choices=[(1, 'Buying'), (2, 'Selling'), (4, 'Credit'), (8, 'Debit')], default=1),
        ),
    ]
