# Generated by Django 3.2.10 on 2022-09-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to='upload/file/')),
            ],
            options={
                'verbose_name_plural': 'UploadFiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ImageField(upload_to='upload/image/')),
            ],
            options={
                'verbose_name_plural': 'UploadFiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfileImages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutletProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_image', to='products.outletproduct')),
            ],
            options={
                'verbose_name_plural': 'OutletProductImages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutletImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=4)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_image', to='outlets.outlet')),
            ],
            options={
                'verbose_name_plural': 'OutletImages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BaseProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.uploadimage')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_image', to='products.baseproduct')),
            ],
            options={
                'verbose_name_plural': 'BaseProductImages',
                'ordering': ['-id'],
            },
        ),
    ]
