# Generated by Django 3.2.10 on 2022-09-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2)),
            ],
            options={
                'verbose_name_plural': 'Attributes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=250)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attribute')),
            ],
            options={
                'verbose_name_plural': 'AttributeValues',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('upc', models.CharField(blank=True, max_length=120)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Active'), (4, 'Credit'), (8, 'Deleted')], default=2)),
                ('photos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'BaseProducts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InternationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('barcode_number', models.CharField(blank=True, max_length=256)),
                ('barcode_formats', models.CharField(blank=True, max_length=256)),
                ('mpn', models.CharField(blank=True, max_length=256)),
                ('model', models.CharField(blank=True, max_length=256)),
                ('asin', models.CharField(blank=True, max_length=256)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('category', models.CharField(blank=True, max_length=256)),
                ('last_child', models.CharField(blank=True, max_length=256)),
                ('manufacturer', models.CharField(blank=True, max_length=256)),
                ('brand', models.CharField(blank=True, max_length=256)),
                ('ingredients', models.CharField(blank=True, max_length=256)),
                ('nutrition_facts', models.CharField(blank=True, max_length=256)),
                ('color', models.CharField(blank=True, max_length=120)),
                ('gender', models.CharField(blank=True, max_length=256)),
                ('material', models.CharField(blank=True, max_length=256)),
                ('pattern', models.CharField(blank=True, max_length=256)),
                ('size', models.CharField(blank=True, max_length=256)),
                ('length', models.CharField(blank=True, max_length=120)),
                ('width', models.CharField(blank=True, max_length=120)),
                ('height', models.CharField(blank=True, max_length=120)),
                ('weight', models.CharField(blank=True, max_length=120)),
                ('release_date', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'InternationProducts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2)),
            ],
            options={
                'verbose_name_plural': 'Measurements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutletProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='', max_length=120)),
                ('px_code', models.CharField(blank=True, max_length=50)),
                ('prod_code', models.CharField(blank=True, max_length=50)),
                ('original_price', models.FloatField(default=0.0)),
                ('selling_price', models.FloatField(default=0.0)),
                ('minimal_price', models.FloatField(default=0.0)),
                ('sale', models.SmallIntegerField(default=0)),
                ('tax_percent', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (4, 'Default'), (8, 'Deleted')], default=2)),
                ('attributes', models.ManyToManyField(blank=True, related_name='attributes', to='products.AttributeValue')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_product', to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='products.baseproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_product_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OutletProducts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_client', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_product', to='products.outletproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(1, 'Income'), (2, 'Purchase'), (4, 'Returned')], default=1)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_product', to='products.outletproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measurement'),
        ),
    ]
