# Generated by Django 3.2.10 on 2022-09-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['-id'], 'verbose_name_plural': '         Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['-id'], 'verbose_name_plural': '        AttributeValues'},
        ),
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': '       BaseProducts'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id'], 'verbose_name_plural': '   Brands'},
        ),
        migrations.AlterModelOptions(
            name='incomeproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': '     IncomeProducts'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-id'], 'verbose_name_plural': '  Measurements'},
        ),
        migrations.AlterModelOptions(
            name='outletproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': '      OutletProducts'},
        ),
        migrations.AlterModelOptions(
            name='salesproduct',
            options={'ordering': ['-id'], 'verbose_name_plural': '    SalesProducts'},
        ),
    ]
