# Generated by Django 3.2.10 on 2022-09-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_alter_transaction_pay_method'),
        ('outlets', '0006_auto_20220910_2144'),
        ('products', '0002_auto_20220909_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(1, 'Buying'), (2, 'Selling'), (4, 'Refund')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_client', to='billings.billingaccount')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlets.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_sell_product', to='products.outletproduct')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_provider', to='billings.billingaccount')),
            ],
            options={
                'verbose_name_plural': '     InOutProduct',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='IncomeProduct',
        ),
    ]
