# Generated by Django 3.2.10 on 2022-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220913_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutproduct',
            name='pay_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (4, 'Cash Card'), (8, 'Credit')], default=1),
        ),
    ]
