# Generated by Django 3.2.10 on 2022-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_inoutproduct_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutproduct',
            name='pay_type',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (4, 'Credit'), (8, 'Cash Card')], default=1),
        ),
    ]
