# Generated by Django 3.2.10 on 2022-09-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0007_alter_inoutproduct_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutproduct',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.currency'),
        ),
    ]
