# Generated by Django 4.1.5 on 2023-01-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_inoutproduct_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'ordering': ['-id'], 'verbose_name_plural': 'AttributeValues'},
        ),
    ]
