# Generated by Django 3.2.10 on 2022-09-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationsmscode',
            options={'ordering': ['-id'], 'verbose_name_plural': '   ActivationSMSCodes'},
        ),
        migrations.AlterModelOptions(
            name='modelpermission',
            options={'ordering': ['-id'], 'verbose_name_plural': ' ModelPermission'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name_plural': '    Users'},
        ),
        migrations.AlterModelOptions(
            name='userpermission',
            options={'verbose_name_plural': '  UserPermissions'},
        ),
    ]
