# Generated by Django 3.2.10 on 2022-09-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_auto_20220909_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='role'),
        ),
        migrations.DeleteModel(
            name='ModelPermission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
