# Generated by Django 3.2.10 on 2022-10-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
    ]
