# Generated by Django 3.2.10 on 2022-10-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20221004_2252'),
        ('dashboard', '0002_selectedpermission_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='dashboard.userrole'),
        ),
        migrations.DeleteModel(
            name='SelectedPermission',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
