# Generated by Django 4.1.5 on 2023-01-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221004_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='first_nme',
        ),
    ]
